name: First Workflow
on: workflow_dispatch 
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: print hello world
        run: echo "Hello World!"
      - name: print farewell
        run: echo "Done - bye!"
      
  
